server {
        listen 80;
        server_name _;

        location / {
                return https://$host$request_uri;
        }

        location /.well-known/ {
                root /var/www/html;
        }

        location /nginx_status {
            allow 51.159.57.162;
            allow 127.0.0.1;
            allow 172.16.0.0/12;
            deny all;
            stub_status;
            access_log /var/log/nginx/access.log;
        }

}

