server {
        listen 0.0.0.0:19113;
        location / {
                proxy_pass http://localhost:9113/;

                auth_basic "";
                auth_basic_user_file "/srv/node-exporter/.htpasswd";
        }
}

