split_clients $request_id $logme {
    5%     1;
    *      0;
}

server {

	listen 443 ssl default_server;
	#	access_log  off;
    access_log /var/log/nginx/subs.access.log combined if=$logerror;

	error_log /var/log/nginx/subs.bdsmlr.com.log;
	client_body_timeout 5s;
    client_header_timeout 5s;

    root /var/www/subdomains/public;

	index index.php index.html index.nginx-debian.html;
    server_name *.bdsmlr.com;
    client_max_body_size 1000M;

	ssl_certificate /etc/ssl/bdsmlr_com_chain.crt;
	ssl_certificate_key /etc/ssl/bdsmlr.key;
	proxy_buffer_size   2128k;
	proxy_buffers   4 11256k;
	proxy_busy_buffers_size   11256k;

    location /phpmyadmin {
        index index.php;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include /etc/nginx/conf.d/snippets/fastcgi-php.conf;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 5900;
    }

    location ^~ /uploads/ {
        expires 365d;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 365d;
        if (!-f $request_filename) {
            rewrite ^ https://bdsmlr.com/$request_uri;
        }
        try_files $uri $uri/ @noimage;
    }

    location ~ ^/uploads/photos/(.*) {
        return 301 $scheme://bdsmlr.com/$request_uri;
    }

    location @noimage {
        rewrite ^ https://bdsmlr.com/$request_uri;
    }

    location ~ \.jpeg$ {
        rewrite ^ https://bdsmlr.com/$request_uri;
    }

    location ~* \.io {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass https://bdsmlr.com:8443;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ~ \.mp4$ {
        try_files $uri $uri/ @novideo;
        mp4;
        mp4_buffer_size 40M;
        mp4_max_buffer_size 100M;
        limit_rate_after 300k;
        limit_rate 350k;
    }

    location @novideo {
        rewrite ^ https://bdsmlr.com/$request_uri;
    }
}
