# Status endpoint for prometheus exporter
server {
    listen 127.0.0.1:8081;
    server_name localhost;

    location /status {
        vhost_traffic_status_display;
        vhost_traffic_status_display_format json;
        allow 127.0.0.1;
        deny all;
    }
}
