server {
  listen 80;
  server_name app-dev.reblogme.com;

  root /srv/static-sites/app-dev.reblogme.com/public;
  index index.html;

  access_log /var/log/nginx/app-dev.reblogme.com.access.log;
  error_log /var/log/nginx/app-dev.reblogme.com.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
