server {
  listen 80;
  server_name chat.bdsmlr.com;

  root /srv/static-sites/chat.bdsmlr.com/public;
  index index.html;

  access_log /var/log/nginx/chat.bdsmlr.com.access.log;
  error_log /var/log/nginx/chat.bdsmlr.com.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
