server {
  listen 80;
  server_name chat.freechat.zone;

  root /srv/static-sites/chat.freechat.zone/public;
  index index.html;

  access_log /var/log/nginx/chat.freechat.zone.access.log;
  error_log /var/log/nginx/chat.freechat.zone.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
