server {
  listen 80;
  server_name cyberstorm.dev;

  root /srv/static-sites/cyberstorm.dev/public;
  index index.html;

  access_log /var/log/nginx/cyberstorm.dev.access.log;
  error_log /var/log/nginx/cyberstorm.dev.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
