server {
  listen 80;
  server_name dev.isexychat.com;

  root /srv/static-sites/dev.isexychat.com/public;
  index index.html;

  access_log /var/log/nginx/dev.isexychat.com.access.log;
  error_log /var/log/nginx/dev.isexychat.com.error.log warn;

  location /blog-images/ {
    alias /srv/static-blobs/dev.isexychat.com/blog-images/;
  }

  location /blog/ {
    alias /srv/static-blobs/dev.isexychat.com/blog/;
    try_files $uri $uri/ =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
