server {
  listen 80;
  server_name dev.adultreviews.today;

  root /srv/static-sites-nonprod/dev.adultreviews.today/public;
  index index.html;

  access_log /var/log/nginx/dev.adultreviews.today.access.log;
  error_log /var/log/nginx/dev.adultreviews.today.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
