server {
  listen 80;
  server_name dev.didgit.dev;

  root /srv/static-sites/dev.didgit.dev/public;
  index index.html;

  access_log /var/log/nginx/dev.didgit.dev.access.log;
  error_log /var/log/nginx/dev.didgit.dev.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
