server {
  listen 80;
  server_name didgit.dev;

  root /srv/static-sites/didgit.dev/public;
  index index.html;

  access_log /var/log/nginx/didgit.dev.access.log;
  error_log /var/log/nginx/didgit.dev.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
