server {
  listen 80;
  server_name isexychat.net;

  root /srv/static-sites/isexychat.net/public;
  index index.html;

  access_log /var/log/nginx/isexychat.net.access.log;
  error_log /var/log/nginx/isexychat.net.error.log warn;

  location /blog-images/ {
    alias /srv/static-blobs/isexychat.net/blog-images/;
  }

  location /blog/ {
    alias /srv/static-blobs/isexychat.net/blog/;
    try_files $uri $uri/ =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
