server {
  listen 80;
  server_name isexychat.app;

  root /srv/static-sites/isexychat.app/public;
  index index.html;

  access_log /var/log/nginx/isexychat.app.access.log;
  error_log /var/log/nginx/isexychat.app.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
