server {
  listen 80;
  server_name legacy.isexychat.com;

  root /srv/static-sites/legacy.isexychat.com/public;
  index index.html;

  access_log /var/log/nginx/legacy.isexychat.com.access.log;
  error_log /var/log/nginx/legacy.isexychat.com.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
