server {
  listen 80;
  server_name reblogme.com;

  root /srv/static-sites/reblogme.com/public;
  index index.html;

  access_log /var/log/nginx/reblogme.com.access.log;
  error_log /var/log/nginx/reblogme.com.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
