server {
  listen 80;
  server_name relax.gg;

  root /srv/static-sites/relax.gg/public;
  index index.html;

  access_log /var/log/nginx/relax.gg.access.log;
  error_log /var/log/nginx/relax.gg.error.log warn;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
