server {

    listen 443 ssl;
    # access_log off;
    access_log /var/log/nginx/api.access.log combined;
    error_log /var/log/nginx/api.bdsmlr.com.log;
    client_body_timeout 5s;
    client_header_timeout 5s;

    root /var/www/api/public;

    index index.php index.html index.nginx-debian.html;
    server_name api.bdsmlr.com;
    client_max_body_size 1000M;

    ssl_certificate /etc/ssl/bdsmlr_com_chain.crt;
    ssl_certificate_key /etc/ssl/bdsmlr.key;

    proxy_buffer_size   2128k;
    proxy_buffers   4 11256k;
    proxy_busy_buffers_size   11256k;

    location / {
        limit_req zone=mylimit burst=5;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ^~ /uploads/ {
        expires 365d;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 365d;
    }

    location ~ \.php$ {
        include /etc/nginx/conf.d/snippets/fastcgi-php.conf;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 5900;
    }
}
