#split_clients $request_id $logme {
#    5%     1;
#    *      0;
#}

log_format dst_hostname '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       '"$http_referer" "$http_user_agent" "$gzip_ratio" $http_host';
server {

    listen 80;
    listen 443 ssl;
    access_log /var/log/nginx/storage_02.access.log dst_hostname buffer=32k flush=1m ;#if=$logme;

    error_log /var/log/nginx/storage_02.error.com.log;
    client_body_timeout 5s;
    client_header_timeout 5s;

    server_name cdn011.bdsmlr.com cdn02.bdsmlr.com cdn09.bdsmlr.com cdn11.bdsmlr.com cdn2.bdsmlr.com cdno011.bdsmlr.com cdno012.bdsmlr.com cdno02.bdsmlr.com cdno08.bdsmlr.com cdno09.bdsmlr.com cdno11.bdsmlr.com vid02.bdsmlr.com cdn59.bdsmlr.com;

    client_max_body_size 1000M;

    ssl_certificate /etc/ssl/bdsmlr_com_chain.crt;
    ssl_certificate_key /etc/ssl/bdsmlr.key;
    proxy_buffer_size   2128k;
    proxy_buffers   4 11256k;
    proxy_busy_buffers_size   11256k;

    location ^~ /uploads/videos/2021/ {
        rewrite ^/(.*) https://cdn013.bdsmlr.com/$1 break;
    }
    location ^~ /uploads/videos/2022/ {
        rewrite ^/(.*) https://cdn013.bdsmlr.com/$1 break;
    }
    location ^~ /uploads/videos/ {
        rewrite ^/(.*) https://cdn101.bdsmlr.com/$1 break;
    }

    location ^~ /uploads/photos/ {
        rewrite ^/(.*) https://cdn101.bdsmlr.com/$1 break;
    }

    location / {
        return 404;
    }
}

server {

    listen 80;
    listen 443 ssl;
    access_log /var/log/nginx/storage_01.access.log dst_hostname buffer=32k flush=1m ;#if=$logme;

    error_log /var/log/nginx/storage_01.error.com.log;
    client_body_timeout 5s;
    client_header_timeout 5s;

    server_name cdn01.bdsmlr.com cdn010.bdsmlr.com cdn03.bdsmlr.com cdn04.bdsmlr.com cdn05.bdsmlr.com cdn06.bdsmlr.com cdn07.bdsmlr.com cdn077.bdsmlr.com cdn08.bdsmlr.com cdn10.bdsmlr.com cdno01.bdsmlr.com cdno010.bdsmlr.com cdno03.bdsmlr.com cdno04.bdsmlr.com cdno05.bdsmlr.com cdno06.bdsmlr.com cdno07.bdsmlr.com cdno10.bdsmlr.com vid01.bdsmlr.com vida.bdsmlr.com ;

    client_max_body_size 1000M;

    ssl_certificate /etc/ssl/bdsmlr_com_chain.crt;
    ssl_certificate_key /etc/ssl/bdsmlr.key;
    proxy_buffer_size   2128k;
    proxy_buffers   4 11256k;
    proxy_busy_buffers_size   11256k;

    location ^~ /uploads/videos/2021/ {
        rewrite ^/(.*) https://cdn013.bdsmlr.com/$1 break;
    }
    location ^~ /uploads/videos/2022/ {
        rewrite ^/(.*) https://cdn013.bdsmlr.com/$1 break;
    }
    location ^~ /uploads/videos/ {
        rewrite ^/(.*) https://cdn101.bdsmlr.com/$1 break;
    }

    location ^~ /uploads/ {
        rewrite ^/(.*) https://cdn101.bdsmlr.com/$1 break;
    }

    location / {
        return 404;
    }
}
