# VTS status endpoint for prometheus nginx-vts-exporter
server {
    listen 8081;
    server_name _;

    location /status {
        vhost_traffic_status_display;
        vhost_traffic_status_display_format json;
    }

    location /metrics {
        vhost_traffic_status_display;
        vhost_traffic_status_display_format prometheus;
    }

    location /health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
