server {
    listen 80;
    listen 443 ssl;
    server_name grafana.i.cyberstorm.dev;

    ssl_certificate     /etc/nginx/certs/certificates/grafana.i.cyberstorm.dev.crt;
    ssl_certificate_key /etc/nginx/certs/certificates/grafana.i.cyberstorm.dev.key;

    location / {
        proxy_pass http://127.0.0.1:3001;
        include /etc/nginx/snippets/proxy.conf;
    }
}

