map $uri $imgproxy_options {
    ~*/300x/   "rs:fill:300:0";
    ~*/100x/   "rs:fill:100:0";
    ~*/400x/   "rs:fill:400:0";
    default    "rs:fill:300:0";
}
upstream imgproxy_upstream { server imgproxy:8080; }
server {
    listen 80;
    server_name media-origin;
    location /uploads/preview/ {
        proxy_cache media_cache;
        proxy_cache_valid 200 30d;
        proxy_intercept_errors on;
        error_page 404 = @imgproxy;
        try_files /non-existent @imgproxy;
    }
    location @imgproxy {
        if ($uri ~* ^/uploads/preview/[^/]+/(.+)$ ) { set $image_path $1; }
        set $imgproxy_url "/unsafe/$imgproxy_options/plain/s3://ocdn012.bdsmlr.com/uploads/$image_path";
        if ($image_path ~* \.gif$) { set $imgproxy_url "$imgproxy_url@mp4"; }
        proxy_pass http://imgproxy_upstream$imgproxy_url;
    }
}
