user nginx;
worker_processes auto;
pid /run/nginx.pid;
events { worker_connections 40000; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    vhost_traffic_status_zone;
    proxy_cache_path /var/cache/nginx/media levels=1:2 keys_zone=media_cache:500m max_size=13000g inactive=30d;
    proxy_temp_path /var/cache/nginx/temp;
    include /etc/nginx/conf.d/sites-enabled/*.conf;
}
