user www-data;
worker_processes auto;

pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # Shared zone for VTS metrics
    vhost_traffic_status_zone;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/snippets/*.conf;
    include /etc/nginx/conf.d/sites-enabled/*.conf;
}
