server {
    listen 80;
    server_name _;

    location /health {
        add_header Content-Type text/plain;
        return 200 "OK";
    }

    location / {
        add_header Content-Type text/plain;
        return 200 "cdn ok";
    }
}
